version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.11.3
commands:
  prepare:
    steps:
      - checkout
      - run: ls package.json | xargs -n1 md5sum > deps.txt
      - run:
          # https://yarnpkg.com/ja/docs/install#linux-tab
          name: Install Yarn@1.12.3
          command: |
            sudo unlink $(which yarn)
            sudo npm i -g yarn@1.12.3
      - run:
          name: Display version of Node.js, npm, Yarn
          command: |
            node -v
            npm -v
            yarn --version

jobs:
  test:
    executor:
      name: default
    steps:
      - prepare
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ .Branch }}-{{ checksum "deps.txt" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ .Branch }}-{{ checksum "deps.txt" }}
      - run: yarn ci-test
      - run: yarn type-check
workflows:
  version: 2.1
  test_deploy:
    jobs:
      - test
